# -*- coding: utf-8 -*-
"""Pertemuan 5 DDP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuWydXDBVldBQ3WsqUEh0GFIiaHSDHoq
"""

print('ini adalah progam sederhana untuk menghitung luas bangun datar')
print("pilih menu angka 1-3 : \n1.persegi\n2.lingkaran\n3.segitiga")
pilihmenu= int(input("silahkan pilih menu dengan mengetikan angka 1-3:"))

match pilihmenu:
    case 1:
        print("ini adalah menu untuk menghitung luas persegi")
        sisi=int(input("silahkan masukan nilai yang mau dihitung "))
        hitung=sisi*sisi
        print(f"luas persegi adalah : {hitung}")
    case 2:
        print("ini adalah menu untuk menghitung luas lingkaran")
        jari=int(input("silahkan masukan nilai yang mau dihitung"))
        hitung=int(22/7*jari*jari)
        print(f"luas lingkaran adalah : {hitung}")
    case 3:
        print("ini adalah menu untuk menghitung luas segitiga")
        alas=int(input("silahkan masukan alas" ))
        tinggi=int(input("silahkan masukan tinggi" ))
        hitung=int(1/2*alas*tinggi)
        print(f"luas segitiga adalah : {hitung}")
    case _:
        print("pilihan tidak valid,silahkan pilih antar 1-3")

# 1. Buat variabel list dengan value : [nama kendaraan,
# JenisKendaraan, cckendaraan, warna kendaraan, roda
# kendaraan]

kendaraan = ['Honda Beat', 'Sepeda Motor', 120,'Biru', 2]
print("Kendaraan saya")
print (kendaraan)
print ("=========")
# tambahkan dari liat tersebut di belakang dengan value : [harga kendaraan, tipe kendaraan]
# kendaraan.append(2000000)
# kendaraan.append("metic")
kendaraan.extend([2000000, "Metic"])
print(kendaraan)
print("=========")
# tambahkan setelah jenis kendaraan dengan value [merk kendaraankendaraan].
kendaraan.insert (2, 'Honda')
print(kendaraan)
print("=========")